### PR TITLE
basic-home-page

### PR DESCRIPTION
**Pull request by arumoy-shome**
- this is a simple homepage
- this is meant as an introduction to Bootstrap
- take a look, once you get the hang of it it's really easy!

@matraj @sujan-sube

### CODE REVIEW

**Comment by arumoy-shome** [comment]
Forgot to update tests :gun:

**Comment by matraj** [comment]
Looks good!

**Comment by sujan-sube** [comment]
:+1: 
Btw, should we fix the test cases before merging or leave it for now, if they're going to change?

**Comment by arumoy-shome** [comment]
Merging this so that @sujan-sube can update tests from a fresh branch!

**Pull request merged**
