### PR TITLE
fixes #48

### LINKED ISSUE #48: Add images to users
- add profile image to users
- default to image provided by Facebook
- fall back to Gravatar
- if all fails, use a placeholder image

### PR DESCRIPTION
**Pull request by arumoy-shome**
# Description
- this PR introduces profile images for users
- goal is to default to the image provided by Facebook
  - to achieve this I have introduces an `image_url:string` column in the User table
  - we will store the image url provided by the Facebook API here
- if that fails, then we will fall back to Gravatar
- if that fails too then we use a placeholder image
# Screenshot

screenshot 2016-02-20 00 47 57

@matraj @sujan-sube

### CODE REVIEW

**Comment by matraj** [comment]
Looks good as well. Why do we have the Gravatar image if we already have a placeholder?

**Comment by sujan-sube** [comment]
I switched to this branch and tried to test out the new profile image. Looks like if the image url is not in the database it defaults to using the gravatar image even if it is missing. So I think we just need to add an additional condition to default to the placeholder image if the gravatar image does not exist.
image

Other than that it looks great!

**Comment by arumoy-shome** [comment]
@matraj we need a placeholder for cases where the user does not have a gravatar image.
@sujan-sube good catch! the default place holder image should be used if gravatar does not have an image, I think something is wrong with the query, let me look into this.

**Comment by arumoy-shome** [comment]
So I decided  to let Gravatar take care of the placeholder, updated screenshots :point_up:
ok to :sheep: this?

**Comment by sujan-sube** [comment]
:+1:

**Pull request merged**
